# Generated by Django 2.0.4 on 2018-04-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translators', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translatorprofile',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='translatorprofile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='translatorprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='translatorprofile',
            name='cost_per_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='translatorprofile',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='translatorprofile',
            name='occupation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
